-- CREATE DATABASE
DROP
DATABASE IF EXISTS TESTINGSYSTEM;
CREATE
DATABASE TESTINGSYSTEM;
USE
TESTINGSYSTEM;

-- CREATE TABLE: DEPARTMENT
CREATE TABLE DEPARTMENT
(
    ID   INT,
    NAME VARCHAR(50)
);

-- CREATE TABLE: POSITION
DROP TABLE IF EXISTS POSITIONS;
CREATE TABLE POSITIONS
(
    ID   INT,
    NAME VARCHAR(50)
);

-- CREATE TABLE: ACCOUNT
CREATE TABLE `ACCOUNT`
(
    ID            INT,
    EMAIL         VARCHAR(50),
    USERNAME      VARCHAR(50),
    FULLNAME      CHAR(50),
    DEPARTMENT_ID INT,
    POSITION_ID   INT,
    CREATE_AT     DATE
);

-- CREATE TABLE: GROUP
CREATE TABLE `GROUP`
(
    ID         INT,
    NAME       VARCHAR(50),
    CREATOR_ID INT,
    CREATE_AT  DATE
);

-- CREATE TABLE: GROUPACCOUNT
CREATE TABLE GROUP_ACCOUNT
(
    GROUP_ID   INT,
    ACCOUNT_ID VARCHAR(50),
    JOIN_AT    DATE
);

-- CREATE TABLE: TYPEQUESTION
CREATE TABLE TYPE_QUESTION
(
    ID   INT,
    NAME VARCHAR(50)
);

-- CREATE TABLE: CATEGORYQUESTION
CREATE TABLE CATEGORY_QUESTION
(
    ID   INT,
    NAME VARCHAR(50)
);

-- CREATE TABLE: QUESTION
CREATE TABLE QUESTION
(
    ID          INT,
    CONTENT     VARCHAR(50),
    CATEGORY_ID INT,
    TYPE_ID     INT,
    CREATOR_ID  INT,
    CREATE_AT   DATE
);

-- CREATE TABLE: ANSWER
CREATE TABLE ANSWER
(
    ID          INT,
    CONTENT     VARCHAR(50),
    QUESTION_ID INT,
    ISCORRECT   BIT
);

-- CREATE TABLE: EXAM2
CREATE TABLE EXAM
(
    ID          INT,
    CODE        VARCHAR(10),
    TITLE       VARCHAR(50),
    CATEGORY_ID INT,
    DURATION    INT,
    CREATOR_ID  INT,
    CREATE_AT   DATE
);

-- CREATE TABLE: EXAMQUESTION
CREATE TABLE EXAMQUESTION
(
    EXAM_ID     INT,
    QUESTION_ID INT
);